### PR TITLE
V1.2.0?

### PR DESCRIPTION
**Pull request by GedMarc**
Resolves for 
- #154 
- Corrects body specification for GET. Allows OPTIONS header wiith bodies
- Removes tests for Feather as outdated (Last update 2015)
- Library is now modular
> - Modules cannot share packages, Utls were trimmed and test classes moved into their own packages
- Allows Generics deserialization with types for Jackson for Collection and Map bodies, query and header parameters
- Correctly identifies Enumerations for Generics and deserialization, and uses Jackson internals for deserialization
- Passes the RequestContext into ValueReader for readers to access information for context driven modifications

### CODE REVIEW

**Comment by GedMarc** [comment]
All tests pass (y)

**Comment by drejc** [comment]
Hi @GedMarc will check out your push request as soon as I have time. Thanks.

**Comment by GedMarc** [comment]
Sorry to be a bother :) just a ping :) 

Would really like to use a released version on central in production :D

**Comment by drejc** [comment]
Thanks for the ping ... will try to squeeze you in ...

**Comment by drejc** [comment]
Hi @GedMarc, I've reviewed your patch, and unfortunately, I can't merge it as it currently stands. The issues are as follows:

You've broken backward compatibility by completely removing the javax annotations.
You've modified the ValueReader interface (I'm not quite sure why the two additional methods are needed).
You've copied dependencies into the project that are meant to remain external.
PS: GET requests can have a body.
I've tried to address these issues, but there are so many changes that it would take me less time to integrate the Jakarta annotations into the project than to revert your changes.

I understand that your changes were made to solve some of your own issues, but in doing so, compatibility has been broken for all existing users. Perhaps consider creating your own solution for this.

**Pull request merged**
